version: '3.5'

services:
  myservice:
    build: 
      context: ./
      dockerfile: Dockerfile
    image: buildmydockerfile:v2
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres:admin@db:5432/a
    ports: 
      - 8080:8080
    depends_on:
      - db
    networks:
      - pgnetwork
  db:
    container_name: postgres-container
    image: postgres
    hostname: postgres
    environment:
      POSTGRES_DB: b 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres
    volumes: 
      - db:/data/postgres
    ports: 
      - 5432:5432
    networks:
      - pgnetwork
    restart: always
  pgadmin:
    container_name: pgadmin-container
    image: dpage/pgadmin4
    environment: 
      PGADMIN_DEFAULT_EMAIL: abc@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    volumes: 
      - pgadmin:/root/.pgadmin
    ports: 
      - 8000:80
    networks:
      - pgnetwork
    restart: always
networks:
  pgnetwork:
    driver: bridge
volumes:
  myservice:
  db:
  pgadmin:
